### ISSUE TITLE
Game broken

### ISSUE THREAD

**Issue by aiturralde** [ANDRESI-Training/github-games-tobias-becker#1]
When attempting to access this at https://ANDRESI-Training.github.io/github-games-tobias-becker, I am getting a 404. This could be caused by a couple of things:

- GitHub Pages needs to be enabled on the  branch. You can fix this in the repository settings.
- The **index.html** file is incorrectly named **inde.html**. We will fix this together in class.

Can you fix the first bullet, please?

**Comment by tobias-becker** [comment]
This resolves issue #1
